name: linux-i686

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install libs required for cross-compiling
      run: |
        sudo apt install -y gcc-multilib g++-multilib

    - name: Install wxWidgets
      run: |
        sudo apt update
        sudo apt install -y libwxgtk3.0-gtk3-dev

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake .. -DARCH=i686
        make

    - name: Zip
      run: |
        zip mandelbrot.zip -r LICENSE README.md mandelbrot
    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: mandelbrot-linux-32bit.zip
        path: mandelbrot.zip
